schema_version = "1.0.0"

id = "mhfrontier_model_importer"
version = "2.2.0"
name = "MHFrontier Model Importer"
tagline = "Import Monster Hunter Frontier model files to Blender"
maintainer = "AsteriskAmpersand <aravuegnitsuga@gmail.com>, Vuze <mhvuze@example.com>, Houmgaor <github@houmgaor.com>"
type = "add-on"

website = "https://github.com/Houmgaor/MHFrontier-Blender-Addon"

tags = ["Import-Export", "Object"]

blender_version_min = "2.8.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
    "SPDX:GPL-3.0-or-later"
]
